#!/usr/bin/env python3
"""Load the waypoint PDDL problem, request a plan and execute it with PlanSys2."""

import sys
from pathlib import Path

from ament_index_python.packages import get_package_share_directory
import rclpy
from rclpy.action import ActionClient
from rclpy.node import Node

from plansys2_msgs.action import ExecutePlan

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent.parent / "common"))
from plansys2_client import PlanSys2ProblemLoader


class WaypointPlanExecutor(PlanSys2ProblemLoader):
    def __init__(self):
        super().__init__()
        self.set_name("waypoint_plan_executor")
        self.execute_plan_client = ActionClient(self, ExecutePlan, "/execute_plan")

    def wait_for_services(self):
        super().wait_for_services()
        self.get_logger().info("Waiting for action /execute_plan...")
        self.execute_plan_client.wait_for_server(timeout_sec=30)

    def execute_plan(self, plan):
        goal = ExecutePlan.Goal()
        goal.plan = plan

        self.get_logger().info("Sending plan to PlanSys2 executor...")
        send_future = self.execute_plan_client.send_goal_async(
            goal, feedback_callback=self.feedback_callback
        )
        rclpy.spin_until_future_complete(self, send_future)
        goal_handle = send_future.result()
        if goal_handle is None:
            raise RuntimeError("Failed to send goal to executor")
        if not goal_handle.accepted:
            raise RuntimeError("Executor rejected the plan")

        result_future = goal_handle.get_result_async()
        rclpy.spin_until_future_complete(self, result_future)
        result_response = result_future.result()
        if result_response is None:
            raise RuntimeError("Failed to receive execution result")
        return result_response.result

    def feedback_callback(self, feedback_msg):
        for item in feedback_msg.feedback.action_execution_status:
            if item.status == item.EXECUTING:
                self.get_logger().info(
                    f"Executing {item.action_full_name}: "
                    f"{item.completion:.2f} - {item.message_status}"
                )


def main():
    base_path = Path(get_package_share_directory("plansys2_waypoint_nav")) / "pddl"
    domain_path = base_path / "domain_waypoint_mission.pddl"
    problem_path = base_path / "problem_waypoint_mission.pddl"

    rclpy.init()
    node = WaypointPlanExecutor()

    try:
        node.wait_for_services()
        node.load_problem(problem_path)
        plan = node.get_plan(domain_path, problem_path)

        print("Plan generated by PlanSys2:")
        for item in plan:
            print(f"{item.time:.3f}: {item.action} [{item.duration:.3f}]")

        result = node.execute_plan(plan)
        print(f"Execution result: {'success' if result.success else 'failure'}")
    except KeyboardInterrupt:
        print("Execution interrupted by user.")
    finally:
        node.destroy_node()
        if rclpy.ok():
            rclpy.shutdown()


if __name__ == "__main__":
    main()
